#
ROUND_DECIMAL_DIGITS = 2
WEEK_DATE_FORMAT = "%b %d, %Y"
DEFAULT_SEL_START_WEEK = "2016W01"
DEFAULT_NUM_WEEKS_AHEAD_OF_CURRENT = 60
DEFAULT_WEEKS_TARGET_IMPORT = 13
LATEST_YEAR = 2025
QUARTER_FORMAT = '%Y.%m'
