# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_user_is_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supercoach',
            field=models.BooleanField(default=False, help_text='Level 1 coach'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_coach',
            field=models.BooleanField(default=False, help_text='Level 2 coach'),
        ),
    ]
