# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 02:16
from __future__ import unicode_literals

import apps.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20160324_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_1_year', models.FloatField(blank=True, null=True)),
                ('rev_2_year', models.FloatField(blank=True, null=True)),
                ('rev_3_year', models.FloatField(blank=True, null=True)),
                ('year_1_lbl', models.CharField(max_length=10)),
                ('year_2_lbl', models.CharField(max_length=10)),
                ('year_3_lbl', models.CharField(max_length=10)),
                ('guarantee_val', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
