# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20160402_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteevalue',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteevalue',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='guaranteevalue',
            name='next_range_start_from',
            field=models.DateField(blank=True, help_text='Next 12 months range start from', null=True),
        ),
    ]
