# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20160410_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteevalue',
            name='guarantee_val',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guaranteevalue',
            name='rev_1_year',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guaranteevalue',
            name='rev_2_year',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guaranteevalue',
            name='rev_3_year',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
