# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20160410_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeEarnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retained_earnings', models.FloatField(blank=True, default=0)),
                ('current_earnings', models.FloatField(blank=True, default=0)),
                ('date', models.DateField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
