# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-07 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20160410_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_learned', models.TextField(verbose_name="The Number 1 Thing I've Learnt From Today's Session")),
                ('goal_1', models.CharField(max_length=100, verbose_name='Goal 1')),
                ('goal_1_achieved', models.BooleanField(default=False, verbose_name='Achieved')),
                ('goal_1_comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('goal_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Goal 2')),
                ('goal_2_achieved', models.BooleanField(default=False, verbose_name='Achieved')),
                ('goal_2_comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('goal_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Goal 3')),
                ('goal_3_achieved', models.BooleanField(default=False, verbose_name='Achieved')),
                ('goal_3_comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('goal_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Goal 4')),
                ('goal_4_achieved', models.BooleanField(verbose_name='Achieved')),
                ('goal_4_comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('field_achievement', models.CharField(blank=True, max_length=255, null=True, verbose_name='My brightest achievement in the week just pass...')),
                ('field_challenge', models.CharField(blank=True, max_length=255, null=True, verbose_name='My main challenge during the week gone...')),
                ('field_learnt', models.CharField(blank=True, max_length=255, null=True, verbose_name='Something that I learnt through reading, listening to a tape, watching a video or living life...')),
                ('field_focus', models.CharField(blank=True, max_length=255, null=True, verbose_name=' At the moment, my greatest focus when working on my business is...')),
                ('field_coach_help', models.CharField(blank=True, max_length=255, null=True, verbose_name='As my coach you can help me out in this next session by...')),
                ('bod_12_program_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('bod_12_program_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone')),
                ('bod_12_program_area_concern', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area of Concern')),
                ('spent_hours', models.CharField(blank=True, max_length=5, null=True, verbose_name='Hours spent working ON my business this last week')),
                ('motivation_percentage', models.CharField(blank=True, max_length=7, null=True, verbose_name='My motivation level is at, %')),
                ('business_is', models.CharField(blank=True, max_length=50, null=True, verbose_name='Business is ')),
                ('lead_generation', models.BooleanField(default=False, verbose_name='Lead Generation')),
                ('conversion_rates', models.BooleanField(default=False, verbose_name='Conversion Rates')),
                ('transactions_number', models.BooleanField(default=False, verbose_name='Number of Transactions')),
                ('avg_sale', models.BooleanField(default=False, verbose_name='Average $ Sale')),
                ('margins', models.BooleanField(default=False, verbose_name='Margins')),
                ('testing', models.BooleanField(default=False, verbose_name='Testing and Measuring')),
                ('documenting', models.BooleanField(default=False, verbose_name='Documenting more Systems')),
                ('training', models.BooleanField(default=False, verbose_name='Training my Team')),
                ('new_marketing', models.BooleanField(default=False, verbose_name='Implemented new Marketing')),
                ('refining_delivery', models.BooleanField(default=False, verbose_name='Refining Delivery & Distribution')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
