# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-18 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_usereventshistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEventsHistory',
            new_name='UserHistoryEvent',
        ),
    ]
