# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-11-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20180419_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowinoutvalue',
            name='order_index',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
