# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-12-27 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_cashflowinoutvalue_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowinout',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
