# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-06 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_cashflowinout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteevalue',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
