# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-06 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_guaranteevalue_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guaranteevalue',
            old_name='next_range_start_from',
            new_name='next_range_start_date',
        ),
    ]
