# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-06 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_rename_next_range_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteevalue',
            name='next_range_end_date',
            field=models.DateField(blank=True, help_text='Next range end date', null=True),
        ),
        migrations.AlterField(
            model_name='guaranteevalue',
            name='next_range_start_date',
            field=models.DateField(blank=True, help_text='Next range start date', null=True),
        ),
    ]
