# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-06 12:45
from __future__ import unicode_literals

from datetime import date
from django.db import migrations


def forwards(apps, schema_editor):

    value_model = apps.get_model('apps', 'GuaranteeValue')

    for value in value_model.objects.filter(next_range_start_date__isnull=False):

        start_date = value.next_range_start_date

        value.next_range_end_date = date(
            start_date.year + 1, month=start_date.month, day=1)

        value.save(update_fields=['next_range_end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_add_next_range_end_date'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop)
    ]
