# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2019-02-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_next_range_end_date_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='guaranteevalue',
            name='minimum_profit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='guaranteevalue',
            name='minimum_profit_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
